workflows:
  android-workflow:
    name: Build Android APK
    environment:
      vars:
        JAVA_VERSION: 11  # Set the Java version if needed

    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - build/outputs/**/*.apk
