workflows:
  android-workflow:
    name: Build Android APK
    environment:
      vars:
        JAVA_VERSION: 11

    scripts:
      - name: Install dependencies
        script: |
          ./gradlew dependencies

      - name: Build APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk  # Adjusted artifact path
